name: Build iOS App (App Store Distribution)

on:
  push:
    branches:
      - main   # adjust to your release branch

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # set your Flutter version

      # 3. Get Flutter dependencies (creates ios/Flutter/Generated.xcconfig)
      - name: Get Flutter dependencies
        run: flutter pub get

      # 4. Install CocoaPods dependencies
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      # 5. Setup code signing
      - name: Setup code signing
        env:
          IOS_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_BASE64 }}
          IOS_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
        run: |
          # Certificate
          echo "$IOS_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$IOS_DISTRIBUTION_CERTIFICATE_PASSWORD" -A
          security list-keychains -d user -s build.keychain
          security default-keychain -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          # Provisioning Profile
          echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(grep -aA1 UUID profile.mobileprovision | grep -io "[-A-F0-9]\{36\}")
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

      # 6. Build the iOS app for App Store
      - name: Build iOS archive
        run: |
          flutter build ipa --release \
            --export-options-plist=ios/exportOptions.plist

      # 7. Upload IPA as artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
