name: iOS Build and Export

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build iOS (no codesign, just prepares Xcode project)
      - name: Flutter build ios
        run: flutter build ios --release --no-codesign

      # Install CocoaPods
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      # Build Xcode Archive
      - name: Build archive
        run: |
          cd ios
          xcodebuild clean archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=R88J8FNA23 \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO \
            SWIFT_TREAT_WARNINGS_AS_ERRORS=NO \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS \
            OTHER_CODE_SIGN_FLAGS="--deep" \
            "PROVISIONING_PROFILE_SPECIFIER[Runner]=ilolo_AppStore"
          cd ..

      # Export IPA
      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/Runner.ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
          cd ..

      # Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ilolo-app-ipa
          path: ios/build/Runner.ipa/*.ipa
