name: iOS Build and Export

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      # 👇 Force Pods to Automatic signing, only Runner uses manual
      - name: Fix Pod Signing
        run: |
          cd ios
          # Reset provisioning profiles for Pods
          for target in $(xcodebuild -list -json | jq -r '.workspace.schemes[]' | grep -v Runner); do
            echo "Setting $target to Automatic signing..."
            /usr/libexec/PlistBuddy -c "Set :objects:XCBuildConfiguration:buildSettings:PROVISIONING_PROFILE_SPECIFIER Automatic" Pods/Pods.xcodeproj/project.pbxproj || true
          done
          cd ..

      - name: Build archive
        run: |
          cd ios
          xcodebuild clean archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=R88J8FNA23 \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO \
            SWIFT_TREAT_WARNINGS_AS_ERRORS=NO \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            PROVISIONING_PROFILE_SPECIFIER=ilolo_AppStore \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS
          cd ..

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/Runner.ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
          cd ..

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ilolo-app-ipa
          path: ios/build/Runner.ipa/*.ipa
