name: iOS Build & Export IPA

on:
  push:
    branches:
      - main   # change if your default branch is different
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0  # set your Flutter version

      # Install Flutter dependencies (this generates ios/Flutter/Generated.xcconfig)
      - name: Flutter pub get
        run: flutter pub get

      # Install CocoaPods dependencies
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install --repo-update

      # Build iOS archive
      - name: Build iOS archive
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild clean archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=R88J8FNA23 \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER=ilolo_AppStore \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO \
            SWIFT_TREAT_WARNINGS_AS_ERRORS=NO \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS

      # Export IPA
      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa \
            -allowProvisioningUpdates

      # Upload IPA artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ilolo-app-ipa
          path: ios/build/ipa/*.ipa
          retention-days: 7
