name: Build iOS IPA

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Create ExportOptions.plist
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>R88J8FNA23</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.ilolo.app</key>
              <string>ilolo_AppStore</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
            <key>manageAppVersionAndBuildNumber</key>
            <true/>
          </dict>
          </plist>
          EOF

      - name: Build archive
        run: |
          cd ios
          xcodebuild clean archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=R88J8FNA23 \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO \
            SWIFT_TREAT_WARNINGS_AS_ERRORS=NO \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            PROVISIONING_PROFILE_SPECIFIER=ilolo_AppStore \
            -allowProvisioningUpdates \
            -destination 'generic/platform=iOS'
          cd ..

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ../ExportOptions.plist \
            -exportPath build/Runner
          cd ..

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ilolo-ipa
          path: ios/build/Runner/Runner.ipa
